/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MidiConfig */

#ifndef _Included_MidiConfig
#define _Included_MidiConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MidiConfig
 * Method:    GetMidiConfig
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MidiConfig_GetMidiConfig
  (JNIEnv *, jobject, jint);

/*
 * Class:     MidiConfig
 * Method:    SetMidiConfig
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_MidiConfig_SetMidiConfig
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
