 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#define _NO_CODE
typedef unsigned char byte;

/* Header for class Midi */
#include "iodata.h"
#include "midicfg.h"

#include "midicontrollerlibrary.h"

// define field names for Midi Config
#define FIELD_MIDI_MESSAGE "midi_message"
#define FIELD_MIDI_CHANNEL "midi_channel"
#define FIELD_DATA_1        "data_1"
#define FIELD_DATA_2        "data_2"
#define FIELD_DATA_1_VARY   "data1_vary"
#define FIELD_MUTE          "mute"
#define FIELD_INVERT        "invert"
#define FIELD_OUT_2         "midi_out2"
#define FIELD_GEN_INIT      "generate_initial"
#define FIELD_HIGH_RES      "high_resolution"
#define FIELD_SCALE         "scale_input"

#define FIELD_LOWER_THRESHOLD "lower_midi"

#define ANA_OUT_RESOULTION_CONFIG_ADDRESS 0x03
#define DIG_IN_CONFIG_ADDRESS 0x04


#define BLUEWAVE_STATUS 0xF9
#define BLUEWAVE_ANA_STATUS -1
#define BLUEWAVE_DIG_STATUS -2

void WriteIntField(JNIEnv *env, jclass config_class, jobject config, const char* field_name, int value)
{
  jfieldID field_id = env->GetFieldID (config_class, field_name, "I");
  env->SetIntField(config, field_id, value);
}

void WriteBoolField(JNIEnv *env, jclass config_class, jobject config, const char* field_name, bool value)
{
  jfieldID field_id = env->GetFieldID (config_class, field_name, "Z");
  env->SetBooleanField(config, field_id, value);
}

int ReadIntField(JNIEnv *env, jclass config_class, jobject config, const char* field_name)
{
  jfieldID field_id = env->GetFieldID (config_class, field_name, "I");
  return env->GetIntField(config, field_id);
}

bool ReadBoolField(JNIEnv *env, jclass config_class, jobject config, const char* field_name)
{
  jfieldID field_id = env->GetFieldID (config_class, field_name, "Z");
  return env->GetBooleanField(config, field_id);
}

/*
 * Class:     Midi
 * Method:    Initialise
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_Midi_Initialise
  (JNIEnv *, jclass)
{
  for (unsigned i = 0; i < 256; i++)
  {
    WriteConfigByte(i, 0xff);
  }
//  SendFactoryDefault();
  printf ("Initialise Patch Editor\r\n");
  InitialisePatchEditor();
}

/*
 * Class:     Midi
 * Method:    DeInitialisePatchEditor
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_Midi_DeInitialisePatchEditor
  (JNIEnv *, jclass)
{
  DeInitialisePatchEditor();
}

/*
 * Class:     Midi
 * Method:    ConfigChanged
 * Signature: ()Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_ConfigChanged
  (JNIEnv *, jclass)
{
  return ConfigChanged();
}

/*
 * Class:     Midi
 * Method:    SetReferenceData
 * Signature: ()Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_SetReferenceData
  (JNIEnv *, jclass)
  {
    SetReferenceData();
    return true;
  }

/*
 * Class:     Midi
 * Method:    LoadConfig
 * Signature: (Ljava/lang/String;)Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_LoadConfig
  (JNIEnv *env, jclass, jstring j_filename)
{
  const char* filename = env->GetStringUTFChars(j_filename, NULL);
  return LoadConfig(filename);
}

/*
 * Class:     Midi
 * Method:    SaveConfig
 * Signature: (Ljava/lang/String;)Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_SaveConfig
  (JNIEnv *env, jclass, jstring j_filename)
{

  const char* filename = env->GetStringUTFChars(j_filename, NULL);
  return SaveConfig(filename);
}

/*
 * Class:     Midi
 * Method:    SendFactoryDefault
 * Signature: (I)Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_SendFactoryDefault
  (JNIEnv *, jclass)
{
  for (unsigned i = 0; i < 256; i++)
  {
    WriteConfigByte(i, 0xff);
  }

  return SendFactoryDefault();
}


/*
 * Class:     Midi
 * Method:    SendReadConfig
 * Signature: (I)Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_SendReadConfig
  (JNIEnv *, jclass)
{
  return SendReadConfig();
}

/*
 * Class:     Midi
 * Method:    CancelWrite
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_Midi_CancelWrite
  (JNIEnv *, jclass)
{
  CancelWrite();
}

/*
 * Class:     Midi
 * Method:    SetOutputDevice
 * Signature: (I)Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_SetOutputDevice
  (JNIEnv *, jclass, jint device)
{
  return SetOutputDevice (device);
}

/*
 * Class:     Midi
 * Method:    SetInputDevice
 * Signature: (I)Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_SetInputDevice
  (JNIEnv *, jclass, jint device)
{
  return SetIntputDevice (device);
}

extern "C" JNIEXPORT jint JNICALL Java_Midi_NumInputDevice
  (JNIEnv *, jclass)
{
   return GetNumMidiInDevices();
}

/*
 * Class:     Midi
 * Method:    NumOutputDevice
 * Signature: ()I
 */
extern "C" JNIEXPORT jint JNICALL Java_Midi_NumOutputDevice
  (JNIEnv *, jclass)
{
  return GetNumMidiOutDevices();
}

/*
 * Class:     Midi
 * Method:    GetInputDeviceName
 * Signature: (Ljava/lang/String;)Z
 */
extern "C" JNIEXPORT jstring JNICALL Java_Midi_GetInputDeviceName
  (JNIEnv *env, jclass, jint index)
{
  char buf [256];
  jstring ret = 0;

  if (GetMidiInputName (index,  buf,  sizeof(buf)))
  {
    ret = env->NewStringUTF(buf);
  }

  return ret;
}

/*
 * Class:     Midi
 * Method:    GetOutputDeviceName
 * Signature: (Ljava/lang/String;)Z
 */
extern "C" JNIEXPORT jstring JNICALL Java_Midi_GetOutputDeviceName
  (JNIEnv *env, jclass, jint index)
{
  char buf [256];
  jstring ret = 0;

  if (GetMidiOutputName (index,  buf,  sizeof(buf)))
  {
    ret = env->NewStringUTF(buf);
  }

  return ret;
}

extern "C" JNIEXPORT void JNICALL Java_MidiConfig_GetMidiConfig
  (JNIEnv *env, jobject config, jint index)
{
  //unsigned config_index = index * 4 ;

  if (index < 64)
  {
    str_midiconfig midi_config;
    ReadMidiConfig (&midi_config, (byte)index);

    // now copy parameters into Java Class Object
    jclass config_class = env->GetObjectClass(config);
    int status = midi_config.status_chan / 16 - 8;
    int channel =  midi_config.status_chan & 0x0f;

    WriteIntField(env, config_class, config, FIELD_MIDI_MESSAGE, status);
    WriteIntField(env, config_class, config, FIELD_MIDI_CHANNEL, channel);
    WriteIntField(env, config_class, config, FIELD_DATA_1, midi_config.data_1);
    WriteIntField(env, config_class, config, FIELD_DATA_2, midi_config.data_2);

    byte flags = midi_config.config_flag;
    bool data_1_vary = flags & DATA_1_VARY_MASK;
    bool mute = flags & MUTE_CONFIG_MASK;
    bool invert = flags & INVERT_VALUE_MASK;
    bool midi_out2 = flags & MIDI_OUTPUT2_MASK;
    bool generate_initial = flags & PRESET_VALUE_FLAG;
    bool high_resolution = flags & HIGH_RES_DUAL_CHAN;
    bool scale_input = flags & VALUE_SCALING_FLAG;

    if (scale_input)
    {
      WriteBoolField(env, config_class, config, FIELD_SCALE, scale_input);
      WriteIntField(env, config_class, config, FIELD_LOWER_THRESHOLD, midi_config.config_flag & 0x7F);
    }
    else
    {
      WriteBoolField(env, config_class, config, FIELD_DATA_1_VARY, data_1_vary);
      WriteBoolField(env, config_class, config, FIELD_MUTE, mute);
      WriteBoolField(env, config_class, config, FIELD_INVERT, invert);
      WriteBoolField(env, config_class, config, FIELD_OUT_2, midi_out2);
      WriteBoolField(env, config_class, config, FIELD_GEN_INIT, generate_initial);
      WriteBoolField(env, config_class, config, FIELD_HIGH_RES, high_resolution);
      WriteBoolField(env, config_class, config, FIELD_SCALE, scale_input);
    }
  }

}

extern "C" JNIEXPORT void JNICALL Java_MidiConfig_SetMidiConfig
  (JNIEnv *env, jobject config, jint index)
{
  //unsigned config_index = index * 4 ;

  if (index < 64)
  {
    str_midiconfig midi_config;

    // now copy parameters into Java Class Object
    jclass config_class = env->GetObjectClass(config);

    byte status, channel;

    status = (byte)((ReadIntField(env, config_class, config, FIELD_MIDI_MESSAGE) + 8) * 0x10);
    channel = (byte) (ReadIntField(env, config_class, config, FIELD_MIDI_CHANNEL));
    midi_config.status_chan = (byte) (status +  channel);

    midi_config.data_1 = (byte) ReadIntField(env, config_class, config, FIELD_DATA_1);
    midi_config.data_2 = (byte) ReadIntField(env, config_class, config, FIELD_DATA_2);

    midi_config.config_flag = 0x0;

    if (ReadBoolField(env, config_class, config, FIELD_SCALE))
    {
      midi_config.config_flag =  ((byte) ReadIntField(env, config_class, config, FIELD_LOWER_THRESHOLD) & 0x7F);
      midi_config.config_flag |= VALUE_SCALING_FLAG;
    }
    else
    {
      if (ReadBoolField(env, config_class, config, FIELD_DATA_1_VARY))
        midi_config.config_flag |= DATA_1_VARY_MASK;

      if (ReadBoolField(env, config_class, config, FIELD_MUTE))
        midi_config.config_flag |= MUTE_CONFIG_MASK;

      if (ReadBoolField(env, config_class, config, FIELD_INVERT))
        midi_config.config_flag |= INVERT_VALUE_MASK;

      if (ReadBoolField(env, config_class, config, FIELD_OUT_2))
        midi_config.config_flag |= MIDI_OUTPUT2_MASK;

      if (ReadBoolField(env, config_class, config, FIELD_GEN_INIT))
        midi_config.config_flag |= PRESET_VALUE_FLAG;


      if (ReadBoolField(env, config_class, config, FIELD_HIGH_RES))
        midi_config.config_flag |= HIGH_RES_DUAL_CHAN;
    }

    WriteMidiConfig(&midi_config, (byte) index);
  }

}

extern "C" JNIEXPORT void JNICALL Java_Midi_SetMidiMerge
  (JNIEnv *, jclass, jboolean merge)
{
  if (merge)
  {
    WriteConfigByte (MIDI_MERGE_ADDRESS, 0xff);
  }
  else
  {
    WriteConfigByte (MIDI_MERGE_ADDRESS, 0x0);
  }
}

/*
 * Class:     Midi
 * Method:    GetMidiMerge
 * Signature: ()Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_GetMidiMerge
  (JNIEnv *, jclass)
{
  return (ReadConfigByte (MIDI_MERGE_ADDRESS));
}

extern "C" JNIEXPORT void JNICALL Java_Midi_SendConfig
  (JNIEnv *, jclass)
{
  SendConfig();
}

extern "C" JNIEXPORT jboolean JNICALL Java_MidiMessage_GetMidiMessage
  (JNIEnv *env, jobject midi_message)
{
  MidiData ret_data;

  bool ret = GetMidiData(&ret_data);

  if (ret)
  {
    jclass message_class = env->GetObjectClass(midi_message);
    int status = ret_data.status / 16 - 8;
    int channel =  ret_data.status & 0x0f;

    if (ret_data.status == BLUEWAVE_STATUS)
    {
      //printf ("Bluewave Data ", ret_data.status);
      channel = ret_data.data1 >> 3; // only lsb

      if (channel < 8)
      {
        status = BLUEWAVE_ANA_STATUS; // we will say analogue
      }
      else
      {
        status = BLUEWAVE_DIG_STATUS;
        channel -= 8;
      }
      int lsb = ret_data.data1 & 0x07;
      int msb = ret_data.data2 << 3;
      int value = lsb + msb;

      WriteIntField(env, message_class, midi_message, FIELD_MIDI_MESSAGE, status);
      WriteIntField(env, message_class, midi_message, FIELD_MIDI_CHANNEL, channel);
      WriteIntField(env, message_class, midi_message, FIELD_DATA_1, value);
      WriteIntField(env, message_class, midi_message, FIELD_DATA_2, 0);

    }
    else
    {
      WriteIntField(env, message_class, midi_message, FIELD_MIDI_MESSAGE, status);
      WriteIntField(env, message_class, midi_message, FIELD_MIDI_CHANNEL, channel);
      WriteIntField(env, message_class, midi_message, FIELD_DATA_1, ret_data.data1);
      WriteIntField(env, message_class, midi_message, FIELD_DATA_2, ret_data.data2);
    }
  }

  return ret;
}

/*
 * Class:     MidiMessage
 * Method:    SetMidiMessage
 * Signature: ()V
 */
extern "C" JNIEXPORT jboolean JNICALL Java_MidiMessage_SetMidiMessage
  (JNIEnv *env, jobject midi_message)
{

  MidiData data;

  // now copy parameters into Java Class Object
  jclass message_class = env->GetObjectClass(midi_message);

  byte status, channel;

  status = (byte)((ReadIntField(env, message_class, midi_message, FIELD_MIDI_MESSAGE) + 8) * 0x10);
  channel = (byte) (ReadIntField(env, message_class, midi_message, FIELD_MIDI_CHANNEL));
  data.status = (byte) (status +  channel);

  data.data1 = (byte) ReadIntField(env, message_class, midi_message, FIELD_DATA_1);
  data.data2 = (byte) ReadIntField(env, message_class, midi_message, FIELD_DATA_2);

  return SendMidiData(data);
}

extern "C" JNIEXPORT jint JNICALL Java_Midi_GetBytesRead
  (JNIEnv *, jclass)
{
  return GetBytesWritten();
}

extern "C" JNIEXPORT jbyte JNICALL Java_Midi_ReadConfigByte
  (JNIEnv *, jclass, jint index)
{
  return (ReadConfigByte (index));
}

extern "C" JNIEXPORT void JNICALL Java_Midi_WriteConfigByte
  (JNIEnv *, jclass, jint index, jbyte value)
{
  if (((unsigned)index) <= 255)
  {
    WriteConfigByte(index, value);
  }

}

extern "C" JNIEXPORT void JNICALL Java_Midi_SetAnaOutEnabled
  (JNIEnv *env, jclass, jint index, jboolean enable)
{
  byte config = ReadConfigByte(DIG_IN_CONFIG_ADDRESS);

  //printf ("Write Config %u\r\n", index);
  if (index < 8)
  {
    byte flag = 1;
    for (unsigned i = 0; i < index; i++)
    {
      flag <<=1;
    }

    if (enable)
    {
      flag ^= 0xff; // flip flag -- bit will be now 0
      config &= flag; // Clear bit
    }
    else
    {
      config |= flag; // set bit
    }

    WriteConfigByte (DIG_IN_CONFIG_ADDRESS, config);
  }

}

extern "C" JNIEXPORT jboolean JNICALL Java_Midi_GetAnaOutEnabled
  (JNIEnv *env, jclass, jint index)
{

  byte config = ReadConfigByte(DIG_IN_CONFIG_ADDRESS);
  unsigned ana_index = unsigned(index);

  //printf ("Read Config %u %02X\r\n", ana_index, config);
  bool ret = false;

  if (ana_index < 8)
  {
    byte flag = 1;
    for (unsigned i = 0; i < ana_index; i++)
    {
      flag <<=1;
    }

    config &= flag; // Have only that bit enabled
    ret = !(config);
  }

  return ret;

}


/*
 * Class:     Midi
 * Method:    SetDeviceNumber
 * Signature: (I)Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_SetDeviceNumber
  (JNIEnv *, jclass, jint device_number)
{
  return SetCurrentDeviceNumber (device_number);
}

/*
 * Class:     Midi
 * Method:    GetDeviceNumber
 * Signature: ()I
 */
extern "C" JNIEXPORT jint JNICALL Java_Midi_GetDeviceNumber
  (JNIEnv *, jclass)
{
  return GetCurrentDeviceNum();
}

/*
 * Class:     Midi
 * Method:    SendDeviceNumber
 * Signature: ()Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_Midi_SendDeviceNumber
  (JNIEnv *, jclass, jint device_number)
{
  return   SendDeviceId(device_number);
}

extern "C" JNIEXPORT jboolean JNICALL Java_Midi_SetUDPDestination
  (JNIEnv *env, jclass, jstring ip_address, jint device_number)
{

  const char* target_address = env->GetStringUTFChars(ip_address, NULL);

  // If we send a Zero Value, we can test for false if they give a port value of zero
  if (device_number)
    return OpenUDPSocket (target_address, device_number);
  else
    return false;
}

extern "C" JNIEXPORT void JNICALL Java_Midi_ProcessConfigByte
  (JNIEnv *env, jclass, jbyte midi_byte)
{
  ProcessMidiByte (midi_byte);
}
